// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' }
import * as $0 from './routes/_app.tsx'
import * as $1 from './routes/feed/index.ts'
import * as $2 from './routes/index.tsx'
import * as $3 from './routes/post/[slug].tsx'
import * as $4 from './routes/sitemap.xml.ts'
import * as $5 from './routes/tag/[tag].tsx'
import * as $6 from './routes/tags/index.tsx'

const manifest = {
	routes: {
		'./routes/_app.tsx': $0,
		'./routes/feed/index.ts': $1,
		'./routes/index.tsx': $2,
		'./routes/post/[slug].tsx': $3,
		'./routes/sitemap.xml.ts': $4,
		'./routes/tag/[tag].tsx': $5,
		'./routes/tags/index.tsx': $6,
	},
	islands: {},
	baseUrl: import.meta.url,
	config,
}

export default manifest
